# -*- coding: utf-8 -*-
"""Youtube Video Transcript Summarization with Hugging Face Transformers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lEoIPVozCmaAUHXLSkJSWEtKVnXEMsf
"""

# from IPython.display import YouTubeVideo
from transformers import pipeline
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled

# youtube_video = "https://www.youtube.com/watch?v=A4OmtyaBHFE"


# video_id = youtube_video.split("=")[1]
# video_id = 'A4OmtyaBHFE'

# YouTubeVideo(video_id)

# Get transcript for the video


def get_transcript(video_id):
    try:
        transcript = YouTubeTranscriptApi.get_transcript(video_id)
        result = ""
        for i in transcript:
            result += ' ' + i['text']
        return result
    except TranscriptsDisabled:
        print("Skipping.")
        return None




