# Generated by Django 4.1.11 on 2023-09-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('video_id', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.TextField()),
                ('sentiment', models.CharField(max_length=100)),
            ],
        ),
    ]
