# Generated by Django 4.1.11 on 2023-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapa',
            name='transcript',
            field=models.TextField(null=True),
        ),
    ]
